name: Build and Run Benchmarks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build_and_run_benchmarks:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Publish
        run: dotnet publish -c Release --verbosity normal -o ./publish/
      - name: Run Benchmarks
        run: dotnet "./publish/UnsafeCollections.Benchmarks.dll" -f "UnsafeCollections.Benchmarks.*"
      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: UnsafeCollections.BenchmarkResults
          path: ./BenchmarkDotNet.Artifacts/results/*.md